apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-uc-service
  labels:
    name: info-uc-service
spec:
  selector:
    matchLabels:
      name: info-uc-service
  replicas: 2
  template:
    metadata:
      labels:
        name: info-uc-service
    spec:
      containers:
      - name: info-uc-service
        image: reg.test.local/library/info-uc-service:0.0.2
      imagePullSecrets:
      - name: registry-secret
