apiVersion: v1
kind: Service
metadata:
  name: info-auth-service
  labels:
    name: info-auth-service
    version: v1
spec:
  ports:
  - name: port8666
    port: 8666
    targetPort: 8666
  selector:
    name: info-auth-service
