kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-rbd-pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: dynamic-ceph-rbd
  resources:
    requests:
      storage: 2Gi
