kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-rdb-claim-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: dynamic-ceph-rdb
  resources:
    requests:
      storage: 2Gi
