apiVersion: v1
kind: Service
metadata:
  name: info-ad-service
  labels:
    serviceName: info-ad-service
    tag: 0.0.2
spec:
  ports:
    
    - name: info-ad-service
      port: 8801
      targetPort: 8801
    
  selector:
    serviceName: info-ad-service
