apiVersion: v1
kind: Service
metadata:
  name: info-admin
  labels:
    serviceName: info-admin
    tag: 0.0.2
spec:
  ports:
    
    - name: info-admin
      port: 7777
      targetPort: 7777
    
  selector:
    serviceName: info-admin
