apiVersion: v1
kind: Service
metadata:
  name: info-auth-service
  labels:
    serviceName: info-auth-service
    tag: 0.0.2
spec:
  ports:
    
    - name: info-auth-service
      port: 8666
      targetPort: 8666
    
  selector:
    serviceName: info-auth-service
