apiVersion: v1
kind: Service
metadata:
  name: info-groupon-service
  labels:
    serviceName: info-groupon-service
    tag: 0.0.2
spec:
  ports:
  - name: port8803
    port: 8803
    targetPort: 8803
  selector:
    serviceName: info-groupon-service
