apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-scheduler-service
  labels:
    serviceName: info-scheduler-service
spec:
  selector:
    matchLabels:
      serviceName: info-scheduler-service
  replicas: 1 
  template:
    metadata:
      labels:
        serviceName: info-scheduler-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: serviceName
                  operator: In
                  values:
                  - info-scheduler-service
      containers:
      - name: info-scheduler-service
        image: reg.test.local/library/info-scheduler-service:0.0.2
        resources:
          requests:
            # cpu: 50m
            memory: 100Mi
          limits:
            # cpu: 500m 
            memory: 1000Mi
      imagePullSecrets:
        - name: registry-secret
