apiVersion: v1
kind: Service
metadata:
  name: info-gateway
  labels:
    serviceName: info-gateway
    tag: 0.0.2
spec:
  ports:
    
    - name: info-gateway
      port: 9999
      targetPort: 9999
    
  selector:
    serviceName: info-gateway
