apiVersion: v1
kind: Service
metadata:
  name: info-news-service
  labels:
    serviceName: info-news-service
    tag: 0.0.2
spec:
  ports:
  - name: port8806
    port: 8806
    targetPort: 8806
  selector:
    serviceName: info-news-service
