apiVersion: v1
kind: Service
metadata:
  name: info-message-service
  labels:
    serviceName: info-message-service
    tag: 0.0.2
spec:
  ports:
  - name: port8555
    port: 8555
    targetPort: 8555
  - name: port9666
    port: 9666
    targetPort: 9666
  selector:
    serviceName: info-message-service
