apiVersion: v1
kind: Service
metadata:
  name: {{ jarName }}
  labels:
    serviceName: {{ jarName }}
    project: ahxx-2.0
    tag: {{ tag }}
spec:
  ports:
    {% for port in ports %}
    - name: {{ port.portName }}
      port: {{ port.port }}
      targetPort: {{ port.port }}
    {% endfor %}
  selector:
    serviceName: {{ jarName }}

