apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-ad-service
  labels:
    serviceName: info-ad-service
spec:
  selector:
    matchLabels:
      serviceName: info-ad-service
  replicas: 4
  template:
    metadata:
      labels:
        serviceName: info-ad-service
    spec:
      containers:
      - name: info-ad-service
        image: reg.test.local/library/info-ad-service:0.0.2
      imagePullSecrets:
      - name: registry-secret
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: serviceName
                  operator: In
                  values:
                  - info-ad-service
