apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-agent-service
  labels:
    serviceName: info-agent-service
spec:
  selector:
    matchLabels:
      serviceName: info-agent-service
  replicas: 2
  template:
    metadata:
      labels:
        serviceName: info-agent-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: serviceName
                  operator: In
                  values:
                  - info-agent-service
      containers:
      - name: info-agent-service
        image: reg.test.local/library/info-agent-service:0.0.2
        resources:
          requests:
            memory: 100Mi
          limits:
            memory: 1000Mi
      imagePullSecrets:
      - name: registry-secret
