apiVersion: v1
kind: Service
metadata:
  name: info-scheduler-service
  labels:
    serviceName: info-scheduler-service
    tag: 0.0.2
spec:
  ports:
  - name: port8777
    port: 8777
    targetPort: 8777
  selector:
    serviceName: info-scheduler-service
