apiVersion: v1
kind: Service
metadata:
  name: info-uc-service
  labels:
    name: info-uc-service
    version: v1
spec:
  ports:
  - name: port8800
    port: 8800
    targetPort: 8800
  selector:
    name: info-uc-service
