apiVersion: v1
kind: Service
metadata:
  name: info-config
  labels:
    serviceName: info-config
    tag: 0.0.2
spec:
  ports:
  - name: port8888
    port: 8888
    targetPort: 8888
  selector:
    serviceName: info-config
