apiVersion: v1
kind: Service
metadata:
  name: info-payment-service
  labels:
    serviceName: info-payment-service
    tag: 0.0.2
spec:
  ports:
  - name: port8808
    port: 8808
    targetPort: 8808
  selector:
    serviceName: info-payment-service
