apiVersion: v1
kind: Service
metadata:
  name: info-store-service
  labels:
    serviceName: info-store-service
    tag: 0.0.2
spec:
  ports:
  - name: port8807
    port: 8807
    targetPort: 8807
  selector:
    serviceName: info-store-service
