# This file should be kept in sync with cluster/gce/coreos/kube-manifests/addons/dashboard/dashboard-controller.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazoncorretto80
  labels:
    app: amazoncorretto80
spec:
  template:
    metadata:
      labels:
        app: amazoncorretto80
    spec:
      containers:
      - name: amazoncorretto80
        image: reg.test.local/library/amazoncorretto:8.0
        command: [ "/bin/sh", "-ce", "tail -f /dev/null" ]
        resources:
          # keep request = limit to keep this container in guaranteed class
      imagePullSecrets:
        - name: registry-secret
  selector:
    matchLabels:
      app: amazoncorretto80
